server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://103.72.145.44:5432/she_said?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: postgres
    password: wangmian787
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    database: 0
    host: 103.72.145.44
    port: 6379
    password: wangmian787
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 3000